from abc import ABC, abstractmethod

from OpenGL.GL import * # type: ignore

class RenderBase(ABC):
    @abstractmethod
    def allocate(self) -> None: ...
    @abstractmethod
    def deallocate(self) -> None: ...
    @abstractmethod
    def update(self) -> None: ...
    @abstractmethod
    def draw_main(self, width: int, height: int) -> None: ...
    @abstractmethod
    def draw_secondary(self, monitor_id: int, width: int, height: int) -> None: ...
    @abstractmethod
    def on_main_window_resize(self, width: int, height: int) -> None: ...