from typing import Protocol

from ._definitions import FrameCallback, SyncCallback, TrackerCallback
from ._usb_camera import UsbCamera


class Cameras(Protocol):
    """Protocol for a coordinated group of cameras.

    Concrete implementations:
      UsbCameras         — real OAK USB cameras
      UsbCameraPlayers   — video-file-backed input (simulated input stream, real camera role)

    Future: IpCameras.
    """

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get(self, device_id: str) -> UsbCamera | None: ...
    def add_frame_callback(self, cb: FrameCallback) -> None: ...
    def add_sync_callback(self, cb: SyncCallback) -> None: ...
    def add_tracker_callback(self, cb: TrackerCallback) -> None: ...
    def add_preview_callback(self, cb: FrameCallback) -> None: ...
